import json

new_vacancies = [
  {
    "slug": "warsaw-agronomist-vertical-farm-101",
    "category": "agriculture",
    "city": "Варшава",
    "city_pl": "Warszawa",
    "city_en": "Warsaw",
    "city_ru": "Варшава",
    "title": "Агроном вертикальної ферми",
    "title_pl": "Agronom Farmy Wertykalnej",
    "title_en": "Vertical Farm Agronomist",
    "title_ru": "Агроном вертикальной фермы",
    "salary": "8000 - 12000 PLN",
    "company": "GreenFuture Urban Farms",
    "shift_ua": "Гнучкий графік",
    "shift_pl": "Elastyczny czas pracy",
    "shift_en": "Flexible hours",
    "shift_ru": "Гибкий график",
    "pattern_ua": "5/2",
    "pattern_pl": "5/2",
    "pattern_en": "5/2",
    "pattern_ru": "5/2",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_en": "By agreement",
    "start_ru": "По договоренности",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_en": "Employment Contract",
    "contract_ru": "Трудовой договор",
    "description_ua": "Шукаємо досвідченого агронома для інноваційної вертикальної ферми в центрі Варшави. Обов'язки включають контроль за гідропонними системами, моніторинг росту рослин, оптимізацію освітлення та клімат-контролю. Потрібна вища освіта в галузі агрономії та досвід роботи з сучасними сільськогосподарськими технологіями. Ми пропонуємо роботу в екологічному стартапі, що швидко розвивається.",
    "description_pl": "Poszukujemy doświadczonego agronoma do innowacyjnej farmy wertykalnej w centrum Warszawy. Obowiązki obejmują kontrolę systemów hydroponicznych, monitorowanie wzrostu roślin, optymalizację oświetlenia i kontroli klimatu. Wymagane wyższe wykształcenie w dziedzinie agronomii oraz doświadczenie w pracy z nowoczesnymi technologiami rolniczymi. Oferujemy pracę w szybko rozwijającym się startupie ekologicznym.",
    "description_en": "We are looking for an experienced agronomist for an innovative vertical farm in the center of Warsaw. Responsibilities include controlling hydroponic systems, monitoring plant growth, optimizing lighting and climate control. Higher education in agronomy and experience with modern agricultural technologies are required. We offer work in a fast-growing ecological startup.",
    "description_ru": "Ищем опытного агронома для инновационной вертикальной фермы в центре Варшавы. Обязанности включают контроль гидропонных систем, мониторинг роста растений, оптимизацию освещения и климат-контроля. Требуется высшее образование в области агрономии и опыт работы с современными сельскохозяйственными технологиями. Мы предлагаем работу в быстрорастущем экологическом стартапе.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "krakow-furniture-restorer-102",
    "category": "crafts",
    "city": "Краків",
    "city_pl": "Kraków",
    "city_en": "Krakow",
    "city_ru": "Краков",
    "title": "Реставратор антикварних меблів",
    "title_pl": "Konserwator Mebli Antycznych",
    "title_en": "Antique Furniture Restorer",
    "title_ru": "Реставратор антикварной мебели",
    "salary": "7000 - 10000 PLN",
    "company": "Krakowskie Antyki",
    "shift_ua": "Одна зміна",
    "shift_pl": "Jedna zmiana",
    "shift_en": "One shift",
    "shift_ru": "Одна смена",
    "pattern_ua": "5/2",
    "pattern_pl": "5/2",
    "pattern_en": "5/2",
    "pattern_ru": "5/2",
    "start_ua": "Негайно",
    "start_pl": "Natychmiast",
    "start_en": "Immediately",
    "start_ru": "Немедленно",
    "contract_ua": "Umowa Zlecenie / Umowa o pracę",
    "contract_pl": "Umowa Zlecenie / Umowa o pracę",
    "contract_en": "Mandate Contract / Employment Contract",
    "contract_ru": "Договор поручения / Трудовой договор",
    "description_ua": "Запрошуємо майстра-реставратора до нашої майстерні в історичному центрі Кракова. Робота з унікальними предметами інтер'єру XVIII-XIX століть. Вимоги: знання старовинних технік обробки дерева, вміння працювати з натуральними лаками та клеями, увага до деталей. Досвід роботи від 5 років є обов'язковим. Надаємо всі необхідні матеріали та інструменти преміум-класу.",
    "description_pl": "Zapraszamy mistrza konserwacji do naszego warsztatu w historycznym centrum Krakowa. Praca z unikalnymi elementami wyposażenia wnętrz z XVIII-XIX wieku. Wymagania: znajomość starych technik obróbki drewna, umiejętność pracy z naturalnymi lakierami i klejami, dbałość o szczegóły. Doświadczenie min. 5 lat jest obowiązkowe. Zapewniamy wszystkie niezbędne materiały i narzędzia premium.",
    "description_en": "We invite a master restorer to our workshop in the historical center of Krakow. Working with unique interior items of the XVIII-XIX centuries. Requirements: knowledge of old wood processing techniques, ability to work with natural varnishes and glues, attention to detail. Minimum 5 years of experience is mandatory. We provide all necessary materials and premium tools.",
    "description_ru": "Приглашаем мастера-реставратора в нашу мастерскую в историческом центре Кракова. Работа с уникальными предметами интерьера XVIII-XIX веков. Требования: знание старинных техник обработки дерева, умение работать с натуральными лаками и клеями, внимание к деталям. Опыт работы от 5 лет обязателен. Предоставляем все необходимые материалы и инструменты премиум-класса.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "lublin-drone-operator-103",
    "category": "technology",
    "city": "Люблін",
    "city_pl": "Lublin",
    "city_en": "Lublin",
    "city_ru": "Люблин",
    "title": "Оператор агродрона",
    "title_pl": "Operator Drona Rolniczego",
    "title_en": "Agricultural Drone Operator",
    "title_ru": "Оператор агродрона",
    "salary": "9000 - 13000 PLN",
    "company": "AeroFarming Solutions",
    "shift_ua": "Гнучкий графік",
    "shift_pl": "Elastyczny czas pracy",
    "shift_en": "Flexible hours",
    "shift_ru": "Гибкий график",
    "pattern_ua": "В залежності від погоди",
    "pattern_pl": "Zależnie od pogody",
    "pattern_en": "Weather dependent",
    "pattern_ru": "В зависимости от погоды",
    "start_ua": "З наступного місяця",
    "start_pl": "Od przyszłego miesiąca",
    "start_en": "From next month",
    "start_ru": "Со следующего месяца",
    "contract_ua": "B2B",
    "contract_pl": "B2B",
    "contract_en": "B2B",
    "contract_ru": "B2B",
    "description_ua": "Шукаємо пілота-оператора дронів для картографування та моніторингу сільськогосподарських угідь у Люблінському воєводстві. Завдання: зйомка полів, створення мультиспектральних карт, аналіз стану врожаю. Обов'язкова наявність європейського сертифікату пілота БПЛА відкритої/спеціальної категорії. Компанія надає службовий автомобіль та найсучасніше обладнання (DJI Agras, Mavic 3 Multispectral).",
    "description_pl": "Poszukujemy pilota-operatora dronów do mapowania i monitorowania gruntów rolnych w województwie lubelskim. Zadania: fotografowanie pól, tworzenie map wielospektralnych, analiza stanu upraw. Obowiązkowe posiadanie europejskiego certyfikatu pilota bezzałogowego statku powietrznego w kategorii otwartej/specjalnej. Firma udostępnia samochód służbowy oraz najnowocześniejszy sprzęt (DJI Agras, Mavic 3 Multispectral).",
    "description_en": "We are looking for a drone pilot-operator for mapping and monitoring agricultural lands in the Lublin Voivodeship. Tasks: field shooting, creating multispectral maps, crop status analysis. Mandatory possession of a European UAV pilot certificate of open/specific category. The company provides a company car and state-of-art equipment (DJI Agras, Mavic 3 Multispectral).",
    "description_ru": "Ищем пилота-оператора дронов для картографирования и мониторинга сельскохозяйственных угодий в Люблинском воеводстве. Задачи: съемка полей, создание мультиспектральных карт, анализ состояния урожая. Обязательно наличие европейского сертификата пилота БПЛА открытой/специальной категории. Компания предоставляет служебный автомобиль и самое современное оборудование (DJI Agras, Mavic 3 Multispectral).",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "gdynia-marine-biologist-104",
    "category": "science",
    "city": "Гдиня",
    "city_pl": "Gdynia",
    "city_en": "Gdynia",
    "city_ru": "Гдыня",
    "title": "Морський біолог",
    "title_pl": "Biolog Morski",
    "title_en": "Marine Biologist",
    "title_ru": "Морской биолог",
    "salary": "8500 - 11000 PLN",
    "company": "Baltic Sea Research Institute",
    "shift_ua": "Повний день",
    "shift_pl": "Pełny etat",
    "shift_en": "Full-time",
    "shift_ru": "Полный день",
    "pattern_ua": "Змішаний",
    "pattern_pl": "Mieszany",
    "pattern_en": "Mixed",
    "pattern_ru": "Смешанный",
    "start_ua": "Через 2 тижні",
    "start_pl": "Za 2 tygodnie",
    "start_en": "In 2 weeks",
    "start_ru": "Через 2 недели",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_en": "Employment Contract",
    "contract_ru": "Трудовой договор",
    "description_ua": "Дослідницький інститут у Гдині шукає морського біолога для участі у проекті з відновлення екосистеми Балтійського моря. Обов'язки: збір зразків води та флори під час експедицій на науковому судні, лабораторний аналіз, підготовка звітів. Вимагається ступінь магістра/доктора наук з морської біології та готовність до кількаденних виходів у море.",
    "description_pl": "Instytut Badawczy w Gdyni poszukuje biologa morskiego do udziału w projekcie odnowy ekosystemu Morza Bałtyckiego. Obowiązki: pobieranie próbek wody i flory podczas ekspedycji na statku badawczym, analiza laboratoryjna, przygotowywanie raportów. Wymagany tytuł magistra/doktora biologii morskiej oraz gotowość do kilkudniowych rejsów.",
    "description_en": "The Research Institute in Gdynia is looking for a marine biologist to participate in the Baltic Sea ecosystem restoration project. Responsibilities: collecting water and flora samples during expeditions on a research vessel, laboratory analysis, preparing reports. A master's/doctoral degree in marine biology and readiness for multi-day trips to sea are required.",
    "description_ru": "Исследовательский институт в Гдыне ищет морского биолога для участия в проекте по восстановлению экосистемы Балтийского моря. Обязанности: сбор образцов воды и флоры во время экспедиций на научном судне, лабораторный анализ, подготовка отчетов. Требуется степень магистра/доктора наук по морской биологии и готовность к многодневным выходам в море.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "poznan-sound-engineer-105",
    "category": "entertainment",
    "city": "Познань",
    "city_pl": "Poznań",
    "city_en": "Poznan",
    "city_ru": "Познань",
    "title": "Звукорежисер (GameDev)",
    "title_pl": "Inżynier Dźwięku (GameDev)",
    "title_en": "Sound Engineer (GameDev)",
    "title_ru": "Звукорежиссер (GameDev)",
    "salary": "10000 - 15000 PLN",
    "company": "PixelQuest Studios",
    "shift_ua": "Гнучкий графік",
    "shift_pl": "Elastyczny czas pracy",
    "shift_en": "Flexible hours",
    "shift_ru": "Гибкий график",
    "pattern_ua": "5/2",
    "pattern_pl": "5/2",
    "pattern_en": "5/2",
    "pattern_ru": "5/2",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_en": "By agreement",
    "start_ru": "По договоренности",
    "contract_ua": "B2B / Umowa o pracę",
    "contract_pl": "B2B / Umowa o pracę",
    "contract_en": "B2B / Employment Contract",
    "contract_ru": "B2B / Трудовой договор",
    "description_ua": "Студія розробки ігор шукає звукорежисера для створення аудіо-ефектів та інтеграції звуку в новий AAA-проект жанру dark fantasy. Робота з Wwise/FMOD, запис фолі-ефектів, зведення та мастеринг. Необхідне портфоліо з прикладами саунд-дизайну для ігор. Ми надаємо сучасну звукозаписну студію в офісі та можливість гібридного формату роботи.",
    "description_pl": "Studio tworzące gry poszukuje inżyniera dźwięku do tworzenia efektów audio i integracji dźwięku w nowym projekcie AAA z gatunku dark fantasy. Praca z Wwise/FMOD, nagrywanie efektów foley, miksowanie i mastering. Wymagane portfolio z przykładami sound designu do gier. Zapewniamy nowoczesne studio nagraniowe w biurze i możliwość pracy hybrydowej.",
    "description_en": "A game development studio is looking for a sound engineer to create audio effects and integrate sound into a new dark fantasy AAA project. Working with Wwise/FMOD, foley recording, mixing and mastering. A portfolio with examples of game sound design is required. We provide a modern recording studio in the office and a hybrid work option.",
    "description_ru": "Студия разработки игр ищет звукорежиссера для создания аудио-эффектов и интеграции звука в новый AAA-проект жанра dark fantasy. Работа с Wwise/FMOD, запись фоли-эффектов, сведение и мастеринг. Необходимо портфолио с примерами саунд-дизайна для игр. Мы предоставляем современную звукозаписывающую студию в офисе и возможность гибридного формата работы.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "zakopane-sommelier-106",
    "category": "hospitality",
    "city": "Закопане",
    "city_pl": "Zakopane",
    "city_en": "Zakopane",
    "city_ru": "Закопане",
    "title": "Сомельє у ресторан високої кухні",
    "title_pl": "Sommelier w restauracji fine dining",
    "title_en": "Sommelier in a fine dining restaurant",
    "title_ru": "Сомелье в ресторан высокой кухни",
    "salary": "9000 - 14000 PLN",
    "company": "Tatra Peak Restaurant",
    "shift_ua": "Вечірні зміни",
    "shift_pl": "Zmiany wieczorne",
    "shift_en": "Evening shifts",
    "shift_ru": "Вечерние смены",
    "pattern_ua": "4/3",
    "pattern_pl": "4/3",
    "pattern_en": "4/3",
    "pattern_ru": "4/3",
    "start_ua": "Негайно",
    "start_pl": "Natychmiast",
    "start_en": "Immediately",
    "start_ru": "Немедленно",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_en": "Employment Contract",
    "contract_ru": "Трудовой договор",
    "description_ua": "Преміальний ресторан у Закопаному шукає харизматичного сомельє. Ваш обов'язок — управління винним погребом (понад 500 позицій), підбір вина до авторського дегустаційного меню від шеф-кухаря, проведення винних вечорів для гостей. Наявність сертифікату WSET Level 3 або CMS Certified Sommelier є обов'язковою. Надаємо безкоштовне проживання у службових апартаментах.",
    "description_pl": "Restauracja premium w Zakopanem poszukuje charyzmatycznego sommeliera. Twoim obowiązkiem będzie zarządzanie piwnicą win (ponad 500 pozycji), dobór wina do autorskiego menu degustacyjnego szefa kuchni, organizacja wieczorów winiarskich dla gości. Wymagany certyfikat WSET Level 3 lub CMS Certified Sommelier. Zapewniamy bezpłatne zakwaterowanie w apartamencie służbowym.",
    "description_en": "A premium restaurant in Zakopane is looking for a charismatic sommelier. Your duties will include managing the wine cellar (over 500 labels), pairing wine with the chef's tasting menu, and hosting wine evenings for guests. A WSET Level 3 or CMS Certified Sommelier certificate is mandatory. We provide free accommodation in a staff apartment.",
    "description_ru": "Премиальный ресторан в Закопане ищет харизматичного сомелье. Ваша обязанность — управление винным погребом (более 500 позиций), подбор вина к авторскому дегустационному меню от шеф-повара, проведение винных вечеров для гостей. Наличие сертификата WSET Level 3 или CMS Certified Sommelier обязательно. Предоставляем бесплатное проживание в служебных апартаментах.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "lodz-chocolatier-107",
    "category": "food",
    "city": "Лодзь",
    "city_pl": "Łódź",
    "city_en": "Lodz",
    "city_ru": "Лодзь",
    "title": "Головний шоколатьє",
    "title_pl": "Główny Chocolatier",
    "title_en": "Chief Chocolatier",
    "title_ru": "Главный шоколатье",
    "salary": "8500 - 12000 PLN",
    "company": "Kakaowa Sztuka",
    "shift_ua": "Ранкові зміни",
    "shift_pl": "Zmiany poranne",
    "shift_en": "Morning shifts",
    "shift_ru": "Утренние смены",
    "pattern_ua": "5/2",
    "pattern_pl": "5/2",
    "pattern_en": "5/2",
    "pattern_ru": "5/2",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_en": "By agreement",
    "start_ru": "По договоренности",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_en": "Employment Contract",
    "contract_ru": "Трудовой договор",
    "description_ua": "Крафтова шоколадна мануфактура в Лодзі шукає головного шоколатьє для розробки нових рецептур цукерок ручної роботи та плиток. Відповідальність за повний цикл виробництва, контроль якості темперування шоколаду, навчання молодшого персоналу. Досвід роботи на аналогічній посаді від 3 років. Запрошуємо творчу особистість, яка закохана в шоколад.",
    "description_pl": "Rzemieślnicza manufaktura czekolady w Łodzi poszukuje głównego chocolatera do opracowywania nowych receptur ręcznie robionych pralin i tabliczek. Odpowiedzialność za pełny cykl produkcyjny, kontrolę jakości temperowania czekolady, szkolenie młodszego personelu. Doświadczenie na podobnym stanowisku min. 3 lata. Zapraszamy kreatywną osobę, zafascynowaną czekoladą.",
    "description_en": "A craft chocolate manufactory in Lodz is looking for a chief chocolatier to develop new recipes for handmade pralines and chocolate bars. Responsibility for the full production cycle, quality control of chocolate tempering, training of junior staff. Experience in a similar position for at least 3 years. We invite a creative person who is in love with chocolate.",
    "description_ru": "Крафтовая шоколадная мануфактура в Лодзи ищет главного шоколатье для разработки новых рецептур конфет ручной работы и плиток. Ответственность за полный цикл производства, контроль качества темперирования шоколада, обучение младшего персонала. Опыт работы на аналогичной должности от 3 лет. Приглашаем творческую личность, влюбленную в шоколад.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "szczecin-wind-turbine-tech-108",
    "category": "engineering",
    "city": "Щецин",
    "city_pl": "Szczecin",
    "city_en": "Szczecin",
    "city_ru": "Щецин",
    "title": "Технік вітрових турбін",
    "title_pl": "Technik Turbin Wiatrowych",
    "title_en": "Wind Turbine Technician",
    "title_ru": "Техник ветровых турбин",
    "salary": "11000 - 16000 PLN",
    "company": "Baltic Wind Energy",
    "shift_ua": "Вахтовий метод",
    "shift_pl": "System rotacyjny",
    "shift_en": "Rotational system",
    "shift_ru": "Вахтовый метод",
    "pattern_ua": "14/14",
    "pattern_pl": "14/14",
    "pattern_en": "14/14",
    "pattern_ru": "14/14",
    "start_ua": "Через місяць",
    "start_pl": "Za miesiąc",
    "start_en": "In a month",
    "start_ru": "Через месяц",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_en": "Employment Contract",
    "contract_ru": "Трудовой договор",
    "description_ua": "Енергетична компанія набирає техніків для обслуговування офшорних вітрових електростанцій у Балтійському морі. Проведення регулярного технічного обслуговування, діагностика та ремонт механічних та електричних систем на висоті. Обов'язкова наявність сертифікатів GWO (Global Wind Organisation), допуск до роботи на висоті. Оплачуємо навчання та страхування життя.",
    "description_pl": "Firma energetyczna poszukuje techników do obsługi morskich farm wiatrowych na Morzu Bałtyckim. Przeprowadzanie regularnej konserwacji, diagnostyka i naprawa systemów mechanicznych i elektrycznych na wysokości. Obowiązkowe posiadanie certyfikatów GWO (Global Wind Organisation), uprawnienia do pracy na wysokości. Opłacamy szkolenia i ubezpieczenie na życie.",
    "description_en": "The energy company is hiring technicians to maintain offshore wind farms in the Baltic Sea. Performing regular maintenance, diagnostics and repair of mechanical and electrical systems at heights. GWO (Global Wind Organisation) certificates and working at heights clearance are mandatory. We pay for training and life insurance.",
    "description_ru": "Энергетическая компания набирает техников для обслуживания офшорных ветровых электростанций в Балтийском море. Проведение регулярного технического обслуживания, диагностика и ремонт механических и электрических систем на высоте. Обязательно наличие сертификатов GWO (Global Wind Organisation), допуск к работе на высоте. Оплачиваем обучение и страхование жизни.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "wroclaw-cybersecurity-analyst-109",
    "category": "it",
    "city": "Вроцлав",
    "city_pl": "Wrocław",
    "city_en": "Wroclaw",
    "city_ru": "Вроцлав",
    "title": "Аналітик з кібербезпеки",
    "title_pl": "Analityk Cyberbezpieczeństwa",
    "title_en": "Cybersecurity Analyst",
    "title_ru": "Аналитик по кибербезопасности",
    "salary": "15000 - 22000 PLN",
    "company": "SecurePay Fintech",
    "shift_ua": "Повний день",
    "shift_pl": "Pełny etat",
    "shift_en": "Full-time",
    "shift_ru": "Полный день",
    "pattern_ua": "5/2",
    "pattern_pl": "5/2",
    "pattern_en": "5/2",
    "pattern_ru": "5/2",
    "start_ua": "Негайно",
    "start_pl": "Natychmiast",
    "start_en": "Immediately",
    "start_ru": "Немедленно",
    "contract_ua": "B2B / Umowa o pracę",
    "contract_pl": "B2B / Umowa o pracę",
    "contract_en": "B2B / Employment Contract",
    "contract_ru": "B2B / Трудовой договор",
    "description_ua": "Фінтех-стартап у Вроцлаві шукає аналітика з кібербезпеки для захисту фінансових транзакцій. Ви будете моніторити мережевий трафік, виявляти вразливості, розробляти стратегії запобігання атакам та проводити пентести. Необхідний досвід роботи в SOC (Security Operations Center), знання SIEM-систем та наявність сертифікатів (CEH, CISSP або аналогів). 100% віддалена робота після випробувального терміну.",
    "description_pl": "Startup fintech we Wrocławiu poszukuje analityka cyberbezpieczeństwa do ochrony transakcji finansowych. Będziesz monitorować ruch sieciowy, wykrywać podatności, opracowywać strategie zapobiegania atakom oraz przeprowadzać pentesty. Wymagane doświadczenie w pracy w SOC (Security Operations Center), znajomość systemów SIEM oraz posiadanie certyfikatów (CEH, CISSP lub podobnych). 100% praca zdalna po okresie próbnym.",
    "description_en": "A fintech startup in Wroclaw is looking for a cybersecurity analyst to protect financial transactions. You will monitor network traffic, identify vulnerabilities, develop attack prevention strategies and conduct pentests. Experience in a SOC (Security Operations Center), knowledge of SIEM systems and certifications (CEH, CISSP or equivalents) are required. 100% remote work after probation.",
    "description_ru": "Финтех-стартап во Вроцлаве ищет аналитика по кибербезопасности для защиты финансовых транзакций. Вы будете мониторить сетевой трафик, выявлять уязвимости, разрабатывать стратегии предотвращения атак и проводить пентесты. Необходим опыт работы в SOC (Security Operations Center), знание SIEM-систем и наличие сертификатов (CEH, CISSP или аналогов). 100% удаленная работа после испытательного срока.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  },
  {
    "slug": "katowice-lighting-designer-110",
    "category": "art",
    "city": "Катовіце",
    "city_pl": "Katowice",
    "city_en": "Katowice",
    "city_ru": "Катовице",
    "title": "Художник по світлу",
    "title_pl": "Realizator Oświetlenia",
    "title_en": "Stage Lighting Designer",
    "title_ru": "Художник по свету",
    "salary": "6500 - 9500 PLN",
    "company": "Teatr Śląski",
    "shift_ua": "Ненормований робочий день",
    "shift_pl": "Nienormowany czas pracy",
    "shift_en": "Irregular working hours",
    "shift_ru": "Ненормированный рабочий день",
    "pattern_ua": "За графіком вистав",
    "pattern_pl": "Zgodnie z harmonogramem spektakli",
    "pattern_en": "According to the performance schedule",
    "pattern_ru": "По графику спектаклей",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_en": "By agreement",
    "start_ru": "По договоренности",
    "contract_ua": "Umowa o dzieło / Umowa o pracę",
    "contract_pl": "Umowa o dzieło / Umowa o pracę",
    "contract_en": "Specific-task contract / Employment Contract",
    "contract_ru": "Договор подряда / Трудовой договор",
    "description_ua": "Сілезький театр у Катовіце запрошує талановитого художника по світлу. Робота над театральними постановками: розробка світлових партитур, програмування світлових консолей (GrandMA2/3), робота під час репетицій та вистав. Потрібне креативне мислення, знання сучасного світлового обладнання та здатність працювати в команді з режисером і сценографом.",
    "description_pl": "Teatr Śląski w Katowicach zaprasza utalentowanego realizatora oświetlenia. Praca przy produkcjach teatralnych: projektowanie partytur świetlnych, programowanie konsolet (GrandMA2/3), praca podczas prób i spektakli. Wymagane kreatywne myślenie, znajomość nowoczesnego sprzętu oświetleniowego oraz umiejętność pracy w zespole z reżyserem i scenografem.",
    "description_en": "The Silesian Theatre in Katowice invites a talented lighting designer. Work on theatrical productions: developing lighting scores, programming lighting consoles (GrandMA2/3), working during rehearsals and performances. Creative thinking, knowledge of modern lighting equipment, and the ability to work in a team with the director and set designer are required.",
    "description_ru": "Силезский театр в Катовице приглашает талантливого художника по свету. Работа над театральными постановками: разработка световых партитур, программирование световых консолей (GrandMA2/3), работа во время репетиций и спектаклей. Требуется креативное мышление, знание современного светового оборудования и способность работать в команде с режиссером и сценографом.",
    "date_posted": "2026-04-08",
    "data_source": "manual",
    "is_generated": False
  }
]

with open('src/content.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Insert the new vacancies at the beginning
data = new_vacancies + data

with open('src/content.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done inserting 10 random unique vacancies")
