import json

new_vacancies = [
  {
    "slug": "krakow-barista-kawarnia-2026",
    "title": "Бариста в сучасну кав'ярню",
    "title_pl": "Barysta w nowoczesnej kawiarni",
    "title_ru": "Бариста в современную кофейню",
    "title_en": "Barista in a modern coffee shop",
    "company": "Kraków Coffee Roasters",
    "category": "hospitality",
    "city": "Краків",
    "salary": "4000-5500 PLN",
    "contract_ua": "Umowa zlecenia",
    "contract_pl": "Umowa zlecenie",
    "contract_ru": "Договор подряда (Umowa zlecenia)",
    "shift_ua": "Змінний графік, 8 годин на день",
    "shift_pl": "Grafik zmianowy, 8 godzin dziennie",
    "shift_ru": "Сменный график, 8 часов в день",
    "pattern_ua": "Ранок/вечір",
    "pattern_pl": "Rano/wieczór",
    "pattern_ru": "Утро/вечер",
    "start_ua": "Одразу",
    "start_pl": "Od zaraz",
    "start_ru": "Сразу",
    "description_ua": "Шукаємо привітного баристу в одну з найпопулярніших кав'ярень Кракова. Основна задача — готувати якісну каву, спілкуватися з гостями та підтримувати чистоту за баром. Досвід вітається, але ми також готові навчити, якщо у вас є велике бажання працювати з кавою.",
    "description_pl": "Szukamy sympatycznego barysty do jednej z najpopularniejszych kawiarni w Krakowie. Głównym zadaniem jest parzenie dobrej kawy, rozmowa z gośćmi oraz dbanie o czystość za barem. Doświadczenie mile widziane, ale chętnie nauczymy, jeśli masz dużą chęć pracy z kawą.",
    "description_ru": "Ищем приветливого бариста в одну из самых популярных кофеен Кракова. Основная задача — готовить качественный кофе, общаться с гостями и поддерживать чистоту за баром. Опыт приветствуется, но мы также готовы обучить, если у вас есть большое желание работать с кофе.",
    "description_en": "We are looking for a friendly barista to join one of the most popular coffee shops in Krakow. The main task is to brew high-quality coffee, chat with guests, and keep the bar clean. Experience is welcome, but we are also ready to teach if you have a great desire to work with coffee.",
    "tasks_ua": ["Приготування кавових напоїв та чаю", "Обслуговування гостей на касі", "Підтримка чистоти робочого місця", "Продаж десертів"],
    "tasks_pl": ["Przygotowywanie napojów kawowych i herbaty", "Obsługa gości przy kasie", "Utrzymanie czystości w miejscu pracy", "Sprzedaż deserów"],
    "tasks_ru": ["Приготовление кофейных напитков и чая", "Обслуживание гостей на кассе", "Поддержание чистоты рабочего места", "Продажа десертов"],
    "requirements_ua": ["Знання польської мови на розмовному рівні (B1+)", "Комунікабельність та позитивний настрій", "Бажання вчитися"],
    "requirements_pl": ["Znajomość języka polskiego na poziomie komunikatywnym (B1+)", "Komunikatywność i pozytywne nastawienie", "Chęć do nauki"],
    "requirements_ru": ["Знание польского языка на разговорном уровне (B1+)", "Коммуникабельность и позитивный настрой", "Желание учиться"],
    "offers_ua": ["Безкоштовна кава під час зміни", "Частка від чайових", "Гнучкий графік, який можна поєднувати з навчанням"],
    "offers_pl": ["Darmowa kawa podczas zmiany", "Udział w napiwkach", "Elastyczny grafik, który można łączyć z nauką"],
    "offers_ru": ["Бесплатный кофе во время смены", "Доля от чаевых", "Гибкий график, который можно совмещать с учебой"],
    "details_ua": ["Стабільна виплата зарплати 10-го числа", "Молодий і дружній колектив", "Можливість кар'єрного росту"],
    "details_pl": ["Stabilna wypłata wynagrodzenia 10. dnia miesiąca", "Młody i przyjazny zespół", "Możliwość rozwoju kariery"],
    "details_ru": ["Стабильная выплата зарплаты 10-го числа", "Молодой и дружный коллектив", "Возможность карьерного роста"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Робота бариста в Кракові — Сучасна кав'ярня",
    "seo_title_pl": "Praca barysta w Krakowie — Nowoczesna kawiarnia",
    "seo_title_ru": "Работа бариста в Кракове — Современная кофейня",
    "seo_title_en": "Barista job in Krakow — Modern coffee shop"
  },
  {
    "slug": "warszawa-dostavka-avto-2026",
    "title": "Водій-кур'єр на службовому авто",
    "title_pl": "Kierowca-kurier na aucie służbowym",
    "title_ru": "Водитель-курьер на служебном авто",
    "title_en": "Courier driver on a company car",
    "company": "Fast Delivery WWA",
    "category": "logistics",
    "city": "Варшава",
    "salary": "5000-7500 PLN",
    "contract_ua": "Umowa zlecenia або B2B",
    "contract_pl": "Umowa zlecenie lub B2B",
    "contract_ru": "Договор подряда или B2B",
    "shift_ua": "10 годин на день",
    "shift_pl": "10 godzin dziennie",
    "shift_ru": "10 часов в день",
    "pattern_ua": "Понеділок - Субота",
    "pattern_pl": "Poniedziałek - Sobota",
    "pattern_ru": "Понедельник - Суббота",
    "start_ua": "Одразу після тестування",
    "start_pl": "Od zaraz po testach",
    "start_ru": "Сразу после тестирования",
    "description_ua": "Шукаємо водія-кур'єра для доставки посилок по Варшаві. Робота на сучасному службовому автомобілі (фургон). Ваше завдання — завантажити посилки зранку на складі та розвезти їх за заданим маршрутом. Маршрут оптимізується додатком. Потрібні дійсні водійські права категорії B.",
    "description_pl": "Szukamy kierowcy-kuriera do dostarczania paczek na terenie Warszawy. Praca na nowoczesnym samochodzie służbowym (bus). Twoim zadaniem jest załadowanie paczek rano w magazynie i rozwiezienie ich wyznaczoną trasą. Trasa jest optymalizowana przez aplikację. Wymagane ważne prawo jazdy kat. B.",
    "description_ru": "Ищем водителя-курьера для доставки посылок по Варшаве. Работа на современном служебном автомобиле (фургон). Ваша задача — загрузить посылки утром на складе и развезти их по заданному маршруту. Маршрут оптимизируется приложением. Требуются действительные водительские права категории B.",
    "description_en": "We are looking for a courier driver to deliver packages in Warsaw. Work on a modern company car (van). Your task is to load packages in the morning at the warehouse and deliver them along the designated route. The route is optimized by the app. Valid category B driver's license required.",
    "tasks_ua": ["Завантаження посилок на складі", "Доставка за адресами", "Робота з мобільним додатком кур'єра", "Підтримка чистоти в автомобілі"],
    "tasks_pl": ["Załadunek paczek w magazynie", "Dostawa pod adresy", "Praca z aplikacją mobilną kuriera", "Utrzymanie czystości w samochodzie"],
    "tasks_ru": ["Загрузка посылок на складе", "Доставка по адресам", "Работа с мобильным приложением курьера", "Поддержание чистоты в автомобиле"],
    "requirements_ua": ["Права категорії B (мінімум 1 рік)", "Орієнтування у Варшаві", "Відповідальність та пунктуальність"],
    "requirements_pl": ["Prawo jazdy kat. B (min. 1 rok)", "Orientacja w Warszawie", "Odpowiedzialność i punktualność"],
    "requirements_ru": ["Права категории B (минимум 1 год)", "Ориентирование в Варшаве", "Ответственность и пунктуальность"],
    "offers_ua": ["Службове авто та оплата палива", "Бонуси за кількість доставлених посилок", "Уніформа"],
    "offers_pl": ["Auto służbowe i opłacone paliwo", "Bonusy za ilość dostarczonych paczek", "Odzież firmowa"],
    "offers_ru": ["Служебное авто и оплата топлива", "Бонусы за количество доставленных посылок", "Униформа"],
    "details_ua": ["Навчання та супровід в перші дні", "Своєчасні виплати", "Офіційне оформлення"],
    "details_pl": ["Szkolenie i wsparcie w pierwszych dniach", "Terminowe wypłaty", "Legalne zatrudnienie"],
    "details_ru": ["Обучение и сопровождение в первые дни", "Своевременные выплаты", "Официальное оформление"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Водій-кур'єр Варшава — Робота з авто компанії",
    "seo_title_pl": "Kierowca-kurier Warszawa — Praca z autem firmy",
    "seo_title_ru": "Водитель-курьер Варшава — Работа с авто компании",
    "seo_title_en": "Courier driver Warsaw — Work with company car"
  },
  {
    "slug": "wroclaw-it-support-2026",
    "title": "Спеціаліст технічної підтримки (IT Support)",
    "title_pl": "Specjalista ds. wsparcia IT (IT Support)",
    "title_ru": "Специалист технической поддержки (IT Support)",
    "title_en": "IT Support Specialist",
    "company": "Tech Global Services",
    "category": "it",
    "city": "Вроцлав",
    "salary": "6000-8500 PLN",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_ru": "Трудовой договор (Umowa o pracę)",
    "shift_ua": "8 годин, з 9:00 до 17:00",
    "shift_pl": "8 godzin, 9:00-17:00",
    "shift_ru": "8 часов, с 9:00 до 17:00",
    "pattern_ua": "Понеділок - П'ятниця",
    "pattern_pl": "Poniedziałek - Piątek",
    "pattern_ru": "Понедельник - Пятница",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_ru": "По договоренности",
    "description_ua": "Запрошуємо в команду спеціаліста технічної підтримки для надання допомоги співробітникам компанії. Ви будете вирішувати проблеми з комп'ютерною технікою, програмним забезпеченням та доступами. Ця позиція ідеально підходить для старту кар'єри в IT. Офіс знаходиться в сучасному бізнес-центрі у Вроцлаві.",
    "description_pl": "Zapraszamy do zespołu specjalistę wsparcia IT, który będzie pomagał pracownikom firmy. Będziesz rozwiązywać problemy ze sprzętem komputerowym, oprogramowaniem i dostępami. To stanowisko jest idealne na start kariery w IT. Biuro znajduje się w nowoczesnym centrum biznesowym we Wrocławiu.",
    "description_ru": "Приглашаем в команду специалиста технической поддержки для оказания помощи сотрудникам компании. Вы будете решать проблемы с компьютерной техникой, программным обеспечением и доступами. Эта позиция идеально подходит для старта карьеры в IT. Офис находится в современном бизнес-центре во Вроцлаве.",
    "description_en": "We invite an IT support specialist to the team to provide assistance to company employees. You will solve problems with computer hardware, software, and access. This position is ideal for starting an IT career. The office is located in a modern business center in Wroclaw.",
    "tasks_ua": ["Обробка заявок користувачів (Helpdesk)", "Налаштування робочих місць для нових працівників", "Діагностика неполадок Windows/Mac", "Керування доступами"],
    "tasks_pl": ["Obsługa zgłoszeń użytkowników (Helpdesk)", "Konfiguracja stanowisk dla nowych pracowników", "Diagnozowanie usterek Windows/Mac", "Zarządzanie dostępami"],
    "tasks_ru": ["Обработка заявок пользователей (Helpdesk)", "Настройка рабочих мест для новых сотрудников", "Диагностика неполадок Windows/Mac", "Управление доступами"],
    "requirements_ua": ["Англійська та польська на рівні B2", "Базове розуміння мереж та ОС", "Вміння спілкуватися з людьми та пояснювати складні речі просто"],
    "requirements_pl": ["Angielski i polski na poziomie B2", "Podstawowe zrozumienie sieci i systemów operacyjnych", "Umiejętność komunikacji z ludźmi i prostego tłumaczenia trudnych rzeczy"],
    "requirements_ru": ["Английский и польский на уровне B2", "Базовое понимание сетей и ОС", "Умение общаться с людьми и объяснять сложные вещи просто"],
    "offers_ua": ["Медичне страхування LuxMed", "Карта Multisport", "Гібридний формат роботи після випробувального терміну"],
    "offers_pl": ["Opieka medyczna LuxMed", "Karta Multisport", "Hybrydowy model pracy po okresie próbnym"],
    "offers_ru": ["Медицинское страхование LuxMed", "Карта Multisport", "Гибридный формат работы после испытательного срока"],
    "details_ua": ["Щорічний перегляд зарплати", "Бюджет на навчання", "Сучасна техніка для роботи"],
    "details_pl": ["Coroczny przegląd wynagrodzenia", "Budżet szkoleniowy", "Nowoczesny sprzęt do pracy"],
    "details_ru": ["Ежегодный пересмотр зарплаты", "Бюджет на обучение", "Современная техника для работы"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "IT Support Вроцлав — Технічна підтримка",
    "seo_title_pl": "IT Support Wrocław — Wsparcie techniczne",
    "seo_title_ru": "IT Support Вроцлав — Техническая поддержка",
    "seo_title_en": "IT Support Wroclaw — Technical support"
  },
  {
    "slug": "poznan-budivelnyk-fasady-2026",
    "title": "Фахівець з фасадних робіт (утеплення)",
    "title_pl": "Specjalista ds. elewacji (docieplenia)",
    "title_ru": "Специалист по фасадным работам (утепление)",
    "title_en": "Facade specialist (insulation)",
    "company": "BudMax Poznań",
    "category": "construction",
    "city": "Познань",
    "salary": "7000-10000 PLN",
    "contract_ua": "Umowa zlecenia",
    "contract_pl": "Umowa zlecenie",
    "contract_ru": "Договор подряда",
    "shift_ua": "10-12 годин",
    "shift_pl": "10-12 godzin",
    "shift_ru": "10-12 часов",
    "pattern_ua": "Понеділок - Субота",
    "pattern_pl": "Poniedziałek - Sobota",
    "pattern_ru": "Понедельник - Суббота",
    "start_ua": "Найближчим часом",
    "start_pl": "W najbliższym czasie",
    "start_ru": "В ближайшее время",
    "description_ua": "Шукаємо досвідчених фасадчиків для роботи на об'єктах у Познані та околицях. Робота полягає в утепленні фасадів пінопластом/мінватою, нанесенні сітки, клею та декоративної штукатурки. Надаємо стабільні об'єкти без простоїв. Працюємо з якісними матеріалами на надійних риштуваннях.",
    "description_pl": "Szukamy doświadczonych elewatorów do pracy na obiektach w Poznaniu i okolicach. Praca polega na docieplaniu elewacji styropianem/wełną, nakładaniu siatki, kleju i tynku strukturalnego. Zapewniamy stabilne obiekty bez przestojów. Pracujemy na dobrych materiałach i solidnych rusztowaniach.",
    "description_ru": "Ищем опытных фасадчиков для работы на объектах в Познани и окрестностях. Работа заключается в утеплении фасадов пенопластом/минватой, нанесении сетки, клея и декоративной штукатурки. Предоставляем стабильные объекты без простоев. Работаем с качественными материалами на надежных лесах.",
    "description_en": "We are looking for experienced facade workers to work on sites in Poznan and the surrounding area. The work consists of insulating facades with styrofoam/mineral wool, applying mesh, glue, and decorative plaster. We provide stable objects without downtime. We work with quality materials on reliable scaffolding.",
    "tasks_ua": ["Монтаж утеплювача", "Армування сіткою", "Нанесення декоративної штукатурки", "Монтаж риштувань"],
    "tasks_pl": ["Montaż ocieplenia", "Zbrojenie siatką", "Nakładanie tynku strukturalnego", "Montaż rusztowań"],
    "tasks_ru": ["Монтаж утеплителя", "Армирование сеткой", "Нанесение декоративной штукатурки", "Монтаж лесов"],
    "requirements_ua": ["Досвід фасадних робіт від 1 року", "Вміння працювати в бригаді", "Відсутність медичних протипоказань до висотних робіт"],
    "requirements_pl": ["Doświadczenie w pracach elewacyjnych min. 1 rok", "Umiejętność pracy w zespole", "Brak przeciwwskazań medycznych do pracy na wysokości"],
    "requirements_ru": ["Опыт фасадных работ от 1 года", "Умение работать в бригаде", "Отсутствие медицинских противопоказаний к высотным работам"],
    "offers_ua": ["Аванси щотижня", "Робочий одяг та інструменти", "Безкоштовне проживання або доплата за своє житло"],
    "offers_pl": ["Zaliczki co tydzień", "Odzież robocza i narzędzia", "Darmowe zakwaterowanie lub dodatek za własne mieszkanie"],
    "offers_ru": ["Авансы еженедельно", "Рабочая одежда и инструменты", "Бесплатное проживание или доплата за свое жилье"],
    "details_ua": ["Доїзд до об'єкта транспортом фірми", "Робота на аккорд (за квадратний метр) або погодинно", "Легальне оформлення"],
    "details_pl": ["Dojazd na obiekt transportem firmowym", "Praca na akord (za metr kwadratowy) lub na godziny", "Legalne zatrudnienie"],
    "details_ru": ["Доезд до объекта транспортом фирмы", "Работа на аккорд (за квадратный метр) или почасово", "Легальное оформление"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Фасадчик Познань — Робота на утепленні",
    "seo_title_pl": "Elewator Poznań — Praca przy dociepleniach",
    "seo_title_ru": "Фасадчик Познань — Работа на утеплении",
    "seo_title_en": "Facade worker Poznan — Insulation job"
  },
  {
    "slug": "gdansk-pakuvanyk-sklad-2026",
    "title": "Працівник складу інтернет-магазину",
    "title_pl": "Pracownik magazynu sklepu internetowego",
    "title_ru": "Работник склада интернет-магазина",
    "title_en": "Warehouse worker for online store",
    "company": "E-commerce Logistics",
    "category": "logistics",
    "city": "Гданськ",
    "salary": "4500-6000 PLN",
    "contract_ua": "Umowa zlecenia",
    "contract_pl": "Umowa zlecenie",
    "contract_ru": "Договор подряда",
    "shift_ua": "Змінний графік, 8-10 годин",
    "shift_pl": "Grafik zmianowy, 8-10 godzin",
    "shift_ru": "Сменный график, 8-10 часов",
    "pattern_ua": "3 зміни (включаючи нічні)",
    "pattern_pl": "3 zmiany (w tym nocki)",
    "pattern_ru": "3 смены (включая ночные)",
    "start_ua": "Постійний набір",
    "start_pl": "Ciągła rekrutacja",
    "start_ru": "Постоянный набор",
    "description_ua": "Запрошуємо на роботу на сучасний чистий склад інтернет-магазину одягу та косметики в Гданську. Робота фізично не важка, підходить як для чоловіків, так і для жінок. Ви будете комплектувати замовлення за допомогою сканера та готувати їх до відправки клієнтам.",
    "description_pl": "Zapraszamy do pracy w nowoczesnym, czystym magazynie sklepu internetowego z odzieżą i kosmetykami w Gdańsku. Praca nie jest ciężka fizycznie, odpowiednia zarówno dla mężczyzn, jak i kobiet. Będziesz kompletować zamówienia za pomocą skanera i przygotowywać je do wysyłki do klientów.",
    "description_ru": "Приглашаем на работу на современный чистый склад интернет-магазина одежды и косметики в Гданьске. Работа физически не тяжелая, подходит как для мужчин, так и для женщин. Вы будете комплектовать заказы с помощью сканера и готовить их к отправке клиентам.",
    "description_en": "We invite you to work in a modern, clean warehouse of an online clothing and cosmetics store in Gdansk. The work is not physically heavy, suitable for both men and women. You will assemble orders using a scanner and prepare them for shipment to customers.",
    "tasks_ua": ["Збір замовлень зі сканером", "Пакування товарів у коробки", "Перевірка якості та комплектності", "Робота з поверненнями"],
    "tasks_pl": ["Zbieranie zamówień ze skanerem", "Pakowanie towarów do kartonów", "Kontrola jakości i kompletności", "Praca ze zwrotami"],
    "tasks_ru": ["Сбор заказов со сканером", "Упаковка товаров в коробки", "Проверка качества и комплектности", "Работа с возвратами"],
    "requirements_ua": ["Уважність до деталей", "Готовність до роботи на ногах", "Знання польської не обов'язкове (меню сканера українською)"],
    "requirements_pl": ["Dbałość o szczegóły", "Gotowość do pracy stojącej", "Znajomość polskiego nie jest wymagana (menu skanera po ukraińsku)"],
    "requirements_ru": ["Внимательность к деталям", "Готовность к работе на ногах", "Знание польского не обязательно (меню сканера на украинском)"],
    "offers_ua": ["Премії за продуктивність", "Доїзд робочим автобусом", "Обід за символічну ціну в їдальні"],
    "offers_pl": ["Premie za produktywność", "Dojazd autobusem pracowniczym", "Obiad za symboliczną kwotę w stołówce"],
    "offers_ru": ["Премии за продуктивность", "Доезд рабочим автобусом", "Обед за символическую цену в столовой"],
    "details_ua": ["Проживання надається (відраховується з ЗП)", "Координатор на місці", "Легальне оформлення та ZUS"],
    "details_pl": ["Zakwaterowanie zapewnione (potrącane z wypłaty)", "Koordynator na miejscu", "Legalne zatrudnienie i ZUS"],
    "details_ru": ["Проживание предоставляется (вычитается из ЗП)", "Координатор на месте", "Легальное оформление и ZUS"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Робота на складі Гданськ — Пакування",
    "seo_title_pl": "Praca na magazynie Gdańsk — Pakowanie",
    "seo_title_ru": "Работа на складе Гданьск — Упаковка",
    "seo_title_en": "Warehouse work Gdansk — Packing"
  },
  {
    "slug": "lodz-zvaryuvalnyk-migmag-2026",
    "title": "Зварювальник MIG/MAG на виробництво",
    "title_pl": "Spawacz MIG/MAG na produkcję",
    "title_ru": "Сварщик MIG/MAG на производство",
    "title_en": "MIG/MAG Welder for production",
    "company": "MetalWorks Łódź",
    "category": "production",
    "city": "Лодзь",
    "salary": "8000-11000 PLN",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_ru": "Трудовой договор",
    "shift_ua": "8-10 годин",
    "shift_pl": "8-10 godzin",
    "shift_ru": "8-10 часов",
    "pattern_ua": "2 зміни",
    "pattern_pl": "2 zmiany",
    "pattern_ru": "2 смены",
    "start_ua": "Після проходження проб у зварювальні",
    "start_pl": "Po przejściu testów spawalniczych",
    "start_ru": "После прохождения проб в сварочной",
    "description_ua": "Великий завод металоконструкцій у місті Лодзь шукає кваліфікованих зварювальників MIG/MAG (135/136). Ви будете працювати над зварюванням середніх та важких сталевих конструкцій на сучасному та безпечному виробництві. Роботодавець цінує якість та забезпечує всіма необхідними засобами захисту.",
    "description_pl": "Duży zakład konstrukcji stalowych w Łodzi szuka wykwalifikowanych spawaczy MIG/MAG (135/136). Będziesz pracować przy spawaniu średnich i ciężkich konstrukcji stalowych na nowoczesnej i bezpiecznej produkcji. Pracodawca ceni jakość i zapewnia wszystkie niezbędne środki ochrony.",
    "description_ru": "Крупный завод металлоконструкций в городе Лодзь ищет квалифицированных сварщиков MIG/MAG (135/136). Вы будете работать над сваркой средних и тяжелых стальных конструкций на современном и безопасном производстве. Работодатель ценит качество и обеспечивает всеми необходимыми средствами защиты.",
    "description_en": "A large steel structures plant in Lodz is looking for qualified MIG/MAG welders (135/136). You will be working on welding medium and heavy steel structures in a modern and safe production facility. The employer values quality and provides all necessary protective equipment.",
    "tasks_ua": ["Зварювання сталевих конструкцій методом MIG/MAG", "Робота з технічним кресленням", "Підготовка металу до зварювання", "Контроль якості швів"],
    "tasks_pl": ["Spawanie konstrukcji stalowych metodą MIG/MAG", "Praca z rysunkiem technicznym", "Przygotowanie metalu do spawania", "Kontrola jakości spoin"],
    "tasks_ru": ["Сварка стальных конструкций методом MIG/MAG", "Работа с техническим чертежом", "Подготовка металла к сварке", "Контроль качества швов"],
    "requirements_ua": ["Досвід зварювання MIG/MAG від 2 років", "Вміння читати технічні креслення", "Наявність актуальних сертифікатів вітається"],
    "requirements_pl": ["Doświadczenie w spawaniu MIG/MAG min. 2 lata", "Umiejętność czytania rysunku technicznego", "Posiadanie aktualnych certyfikatów mile widziane"],
    "requirements_ru": ["Опыт сварки MIG/MAG от 2 лет", "Умение читать технические чертежи", "Наличие актуальных сертификатов приветствуется"],
    "offers_ua": ["Висока погодинна ставка", "Безкоштовний спецодяг високої якості", "Допомога з поновленням сертифікатів"],
    "offers_pl": ["Wysoka stawka godzinowa", "Darmowa odzież robocza wysokiej jakości", "Pomoc w odnowieniu certyfikatów"],
    "offers_ru": ["Высокая почасовая ставка", "Бесплатная спецодежда высокого качества", "Помощь с обновлением сертификатов"],
    "details_ua": ["Медичне страхування", "Допомога з картою побиту", "Проживання в комфортних умовах (окремі кімнати для спеціалістів)"],
    "details_pl": ["Opieka medyczna", "Pomoc z kartą pobytu", "Zakwaterowanie w komfortowych warunkach (osobne pokoje dla specjalistów)"],
    "details_ru": ["Медицинское страхование", "Помощь с картой побыту", "Проживание в комфортных условиях (отдельные комнаты для специалистов)"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Зварювальник Лодзь MIG/MAG — Робота на заводі",
    "seo_title_pl": "Spawacz Łódź MIG/MAG — Praca na zakładzie",
    "seo_title_ru": "Сварщик Лодзь MIG/MAG — Работа на заводе",
    "seo_title_en": "Welder Lodz MIG/MAG — Factory work"
  },
  {
    "slug": "lublin-oficiant-restoran-2026",
    "title": "Офіціант в ресторан європейської кухні",
    "title_pl": "Kelner w restauracji z kuchnią europejską",
    "title_ru": "Официант в ресторан европейской кухни",
    "title_en": "Waiter in a European cuisine restaurant",
    "company": "Taste of Europe",
    "category": "hospitality",
    "city": "Люблін",
    "salary": "4000-6000 PLN",
    "contract_ua": "Umowa zlecenia",
    "contract_pl": "Umowa zlecenie",
    "contract_ru": "Договор подряда",
    "shift_ua": "Позмінно",
    "shift_pl": "Zmianowo",
    "shift_ru": "Посменно",
    "pattern_ua": "2 через 2 або гнучкий",
    "pattern_pl": "2 na 2 lub elastyczny",
    "pattern_ru": "2 через 2 или гибкий",
    "start_ua": "Одразу",
    "start_pl": "Od zaraz",
    "start_ru": "Сразу",
    "description_ua": "Елегантний ресторан у центрі Любліна шукає офіціантів. Ми пропонуємо роботу в атмосферному закладі з лояльними гостями та стабільним потоком чайових. Це чудова можливість для тих, хто любить спілкуватися з людьми та створювати позитивні емоції. Досвід бажаний, але не обов'язковий.",
    "description_pl": "Elegancka restauracja w centrum Lublina szuka kelnerów. Oferujemy pracę w klimatycznym lokalu z lojalnymi gośćmi i stabilnym przepływem napiwków. To świetna okazja dla tych, którzy lubią rozmawiać z ludźmi i tworzyć pozytywne emocje. Doświadczenie mile widziane, ale nie obowiązkowe.",
    "description_ru": "Элегантный ресторан в центре Люблина ищет официантов. Мы предлагаем работу в атмосферном заведении с лояльными гостями и стабильным потоком чаевых. Это отличная возможность для тех, кто любит общаться с людьми и создавать позитивные эмоции. Опыт желателен, но не обязателен.",
    "description_en": "An elegant restaurant in the center of Lublin is looking for waiters. We offer work in an atmospheric establishment with loyal guests and a steady flow of tips. This is a great opportunity for those who love interacting with people and creating positive emotions. Experience is preferred but not required.",
    "tasks_ua": ["Прийом замовлень та подача страв", "Консультування гостей щодо меню", "Підтримка чистоти в залі", "Робота з касовим апаратом/терміналом"],
    "tasks_pl": ["Przyjmowanie zamówień i podawanie dań", "Doradzanie gościom w zakresie menu", "Utrzymanie czystości na sali", "Praca z kasą/terminalem"],
    "tasks_ru": ["Прием заказов и подача блюд", "Консультирование гостей по меню", "Поддержание чистоты в зале", "Работа с кассовым аппаратом/терминалом"],
    "requirements_ua": ["Комунікативна польська мова", "Охайний зовнішній вигляд", "Ввічливість та стресостійкість"],
    "requirements_pl": ["Komunikatywny język polski", "Schludny wygląd zewnętrzny", "Uprzejmość i odporność na stres"],
    "requirements_ru": ["Коммуникативный польский язык", "Опрятный внешний вид", "Вежливость и стрессоустойчивость"],
    "offers_ua": ["Всі чайові ваші", "Безкоштовне харчування", "Знижки на меню закладу для працівників"],
    "offers_pl": ["Wszystkie napiwki są twoje", "Darmowe wyżywienie", "Zniżki na menu lokalu dla pracowników"],
    "offers_ru": ["Все чаевые ваши", "Бесплатное питание", "Скидки на меню заведения для работников"],
    "details_ua": ["Можливість поєднувати з навчанням", "Дружня атмосфера", "Допомога з виготовленням санітарної книжки"],
    "details_pl": ["Możliwość łączenia z nauką", "Przyjazna atmosfera", "Pomoc w wyrobieniu książeczki sanepidowskiej"],
    "details_ru": ["Возможность совмещать с учебой", "Дружеская атмосфера", "Помощь с оформлением санитарной книжки"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Офіціант Люблін — Робота в ресторані",
    "seo_title_pl": "Kelner Lublin — Praca w restauracji",
    "seo_title_ru": "Официант Люблин — Работа в ресторане",
    "seo_title_en": "Waiter Lublin — Restaurant job"
  },
  {
    "slug": "szczecin-prakivnyk-vyr-2026",
    "title": "Працівник на виробництво пластикових деталей",
    "title_pl": "Pracownik produkcji detali plastikowych",
    "title_ru": "Работник на производство пластиковых деталей",
    "title_en": "Production worker for plastic details",
    "company": "PlastForm Industry",
    "category": "production",
    "city": "Щецін",
    "salary": "5000-6500 PLN",
    "contract_ua": "Umowa o pracę",
    "contract_pl": "Umowa o pracę",
    "contract_ru": "Трудовой договор",
    "shift_ua": "8 годин",
    "shift_pl": "8 godzin",
    "shift_ru": "8 часов",
    "pattern_ua": "3 зміни (включаючи нічні)",
    "pattern_pl": "3 zmiany (w tym nocki)",
    "pattern_ru": "3 смены (включая ночные)",
    "start_ua": "Одразу",
    "start_pl": "Od zaraz",
    "start_ru": "Сразу",
    "description_ua": "Шукаємо працівників на стабільне виробництво пластикових деталей (автомобільна промисловість та побутова техніка) у Щеціні. Робота не вимагає спеціальних навичок, всього навчають на місці. Основний обов'язок — контроль якості вироблених деталей та їх пакування. Завод сучасний, чистий, без шкідливих запахів.",
    "description_pl": "Szukamy pracowników na stabilną produkcję detali plastikowych (automotive i AGD) w Szczecinie. Praca nie wymaga specjalnych umiejętności, wszystkiego uczymy na miejscu. Główny obowiązek to kontrola jakości wyprodukowanych detali i ich pakowanie. Zakład jest nowoczesny, czysty, bez szkodliwych zapachów.",
    "description_ru": "Ищем работников на стабильное производство пластиковых деталей (автомобильная промышленность и бытовая техника) в Щецине. Работа не требует специальных навыков, всему обучают на месте. Основная обязанность — контроль качества произведенных деталей и их упаковка. Завод современный, чистый, без вредных запахов.",
    "description_en": "We are looking for workers for a stable production of plastic details (automotive and home appliances) in Szczecin. The work does not require special skills, everything is taught on site. The main duty is quality control of the produced details and their packaging. The factory is modern, clean, with no harmful odors.",
    "tasks_ua": ["Зняття деталей з машини", "Візуальний контроль якості", "Обрізка надлишків пластику", "Пакування в коробки"],
    "tasks_pl": ["Zdejmowanie detali z maszyny", "Wizualna kontrola jakości", "Obcinanie nadmiaru plastiku", "Pakowanie w kartony"],
    "tasks_ru": ["Снятие деталей с машины", "Визуальный контроль качества", "Обрезка излишков пластика", "Упаковка в коробки"],
    "requirements_ua": ["Хороший зір (для перевірки деталей)", "Готовність до роботи в 3 зміни", "Відповідальність"],
    "requirements_pl": ["Dobry wzrok (do sprawdzania detali)", "Gotowość do pracy na 3 zmiany", "Odpowiedzialność"],
    "requirements_ru": ["Хорошее зрение (для проверки деталей)", "Готовность к работе в 3 смены", "Ответственность"],
    "offers_ua": ["Доплата за нічні зміни (+20%)", "Премія за відвідуваність", "Службовий автобус з центру міста"],
    "offers_pl": ["Dodatek za nocki (+20%)", "Premia frekwencyjna", "Autobus pracowniczy z centrum miasta"],
    "offers_ru": ["Доплата за ночные смены (+20%)", "Премия за посещаемость", "Служебный автобус из центра города"],
    "details_ua": ["Повноцінний соціальний пакет (лікарняні, відпустки)", "Житло надається за бажанням", "Безкоштовний робочий одяг"],
    "details_pl": ["Pełny pakiet socjalny (zwolnienia lekarskie, urlopy)", "Zakwaterowanie zapewnione na życzenie", "Darmowa odzież robocza"],
    "details_ru": ["Полноценный социальный пакет (больничные, отпуска)", "Жилье предоставляется по желанию", "Бесплатная рабочая одежда"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Виробництво Щецін — Працівник заводу",
    "seo_title_pl": "Produkcja Szczecin — Pracownik zakładu",
    "seo_title_ru": "Производство Щецин — Работник завода",
    "seo_title_en": "Production Szczecin — Factory worker"
  },
  {
    "slug": "katowice-prykashchyk-2026",
    "title": "Прибиральник / Прибиральниця офісів",
    "title_pl": "Sprzątacz / Sprzątaczka biur",
    "title_ru": "Уборщик / Уборщица офисов",
    "title_en": "Office Cleaner",
    "company": "CleanPro Service",
    "category": "cleaning",
    "city": "Катовіце",
    "salary": "3500-4500 PLN",
    "contract_ua": "Umowa zlecenia",
    "contract_pl": "Umowa zlecenie",
    "contract_ru": "Договор подряда",
    "shift_ua": "4-8 годин",
    "shift_pl": "4-8 godzin",
    "shift_ru": "4-8 часов",
    "pattern_ua": "Ранкові або вечірні години",
    "pattern_pl": "Godziny poranne lub wieczorne",
    "pattern_ru": "Утренние или вечерние часы",
    "start_ua": "За домовленістю",
    "start_pl": "Do uzgodnienia",
    "start_ru": "По договоренности",
    "description_ua": "Клінінгова компанія шукає персонал для прибирання сучасних офісних приміщень у Катовіце. Можливий гнучкий графік, що дозволяє працювати неповний день або поєднувати з іншою роботою. Ми забезпечуємо всіма необхідними професійними засобами та технікою.",
    "description_pl": "Firma sprzątająca szuka personelu do sprzątania nowoczesnych powierzchni biurowych w Katowicach. Możliwy elastyczny grafik, pozwalający na pracę na pół etatu lub łączenie z inną pracą. Zapewniamy wszystkie niezbędne profesjonalne środki i sprzęt.",
    "description_ru": "Клининговая компания ищет персонал для уборки современных офисных помещений в Катовице. Возможен гибкий график, позволяющий работать неполный день или совмещать с другой работой. Мы обеспечиваем всеми необходимыми профессиональными средствами и техникой.",
    "description_en": "A cleaning company is looking for personnel to clean modern office spaces in Katowice. A flexible schedule is possible, allowing you to work part-time or combine it with another job. We provide all the necessary professional products and equipment.",
    "tasks_ua": ["Вологе та сухе прибирання офісів", "Винесення сміття", "Прибирання санвузлів та кухонь", "Поповнення витратних матеріалів (мило, папір)"],
    "tasks_pl": ["Mycie na mokro i sucho biur", "Wynoszenie śmieci", "Sprzątanie toalet i kuchni", "Uzupełnianie materiałów eksploatacyjnych (mydło, papier)"],
    "tasks_ru": ["Влажная и сухая уборка офисов", "Вынос мусора", "Уборка санузлов и кухонь", "Пополнение расходных материалов (мыло, бумага)"],
    "requirements_ua": ["Охайність та відповідальність", "Досвід у клінінгу вітається, але не є обов'язковим", "Відсутність алергії на миючі засоби"],
    "requirements_pl": ["Schludność i odpowiedzialność", "Doświadczenie w sprzątaniu mile widziane, ale nie obowiązkowe", "Brak alergii na środki czystości"],
    "requirements_ru": ["Опрятность и ответственность", "Опыт в клининге приветствуется, но не обязателен", "Отсутствие аллергии на моющие средства"],
    "offers_ua": ["Гнучкий графік", "Стабільна оплата", "Робота в одному закріпленому офісі"],
    "offers_pl": ["Elastyczny grafik", "Stabilne wynagrodzenie", "Praca w jednym przypisanym biurze"],
    "offers_ru": ["Гибкий график", "Стабильная оплата", "Работа в одном закрепленном офисе"],
    "details_ua": ["Забезпечуємо робочим одягом", "Можливість додаткових годин", "Приємний колектив"],
    "details_pl": ["Zapewniamy odzież roboczą", "Możliwość nadgodzin", "Przyjemny zespół"],
    "details_ru": ["Обеспечиваем рабочей одеждой", "Возможность дополнительных часов", "Приятный коллектив"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Прибирання Катовіце — Робота в клінінгу",
    "seo_title_pl": "Sprzątanie Katowice — Praca w serwisie sprzątającym",
    "seo_title_ru": "Уборка Катовице — Работа в клининге",
    "seo_title_en": "Cleaning Katowice — Cleaning service job"
  },
  {
    "slug": "bydgoszcz-montazhnyk-2026",
    "title": "Монтажник сонячних панелей",
    "title_pl": "Instalator paneli fotowoltaicznych",
    "title_ru": "Монтажник солнечных панелей",
    "title_en": "Solar panel installer",
    "company": "EcoSun Power",
    "category": "construction",
    "city": "Бидгощ",
    "salary": "7500-11000 PLN",
    "contract_ua": "Umowa zlecenia / B2B",
    "contract_pl": "Umowa zlecenie / B2B",
    "contract_ru": "Договор подряда / B2B",
    "shift_ua": "10 годин",
    "shift_pl": "10 godzin",
    "shift_ru": "10 часов",
    "pattern_ua": "Понеділок - Субота",
    "pattern_pl": "Poniedziałek - Sobota",
    "pattern_ru": "Понедельник - Суббота",
    "start_ua": "Після проходження інструктажу",
    "start_pl": "Po przejściu szkolenia",
    "start_ru": "После прохождения инструктажа",
    "description_ua": "Шукаємо монтажників сонячних електростанцій для роботи на дахах приватних будинків та підприємств. Робота у сфері відновлюваної енергетики — це стабільність та високий заробіток. Досвід покрівельних або електромонтажних робіт буде великою перевагою.",
    "description_pl": "Szukamy instalatorów elektrowni słonecznych do pracy na dachach domów prywatnych i przedsiębiorstw. Praca w branży odnawialnych źródeł energii to stabilność i wysokie zarobki. Doświadczenie w pracach dekarskich lub elektromontażowych będzie dużym atutem.",
    "description_ru": "Ищем монтажников солнечных электростанций для работы на крышах частных домов и предприятий. Работа в сфере возобновляемой энергетики — это стабильность и высокий заработок. Опыт кровельных или электромонтажных работ будет большим преимуществом.",
    "description_en": "We are looking for solar power plant installers to work on the roofs of private houses and businesses. Working in the renewable energy sector means stability and high earnings. Experience in roofing or electrical work will be a great advantage.",
    "tasks_ua": ["Монтаж конструкцій кріплення на даху", "Встановлення сонячних панелей", "Прокладання кабелів", "Підключення інверторів (для електриків)"],
    "tasks_pl": ["Montaż konstrukcji wsporczych na dachu", "Instalacja paneli fotowoltaicznych", "Układanie okablowania", "Podłączanie falowników (dla elektryków)"],
    "tasks_ru": ["Монтаж крепежных конструкций на крыше", "Установка солнечных панелей", "Прокладка кабелей", "Подключение инверторов (для электриков)"],
    "requirements_ua": ["Відсутність страху висоти", "Фізична витривалість", "Права категорії B (для бригадира)"],
    "requirements_pl": ["Brak lęku wysokości", "Wytrzymałość fizyczna", "Prawo jazdy kat. B (dla brygadzisty)"],
    "requirements_ru": ["Отсутствие страха высоты", "Физическая выносливость", "Права категории B (для бригадира)"],
    "offers_ua": ["Висока ставка на аккорд або погодинно", "Навчання за рахунок компанії", "Спецодяг та страховка"],
    "offers_pl": ["Wysoka stawka na akord lub na godziny", "Szkolenia na koszt firmy", "Odzież robocza i ubezpieczenie"],
    "offers_ru": ["Высокая ставка на аккорд или почасово", "Обучение за счет компании", "Спецодежда и страховка"],
    "details_ua": ["Командировочні виплати (дієти)", "Допомога з житлом у відрядженнях", "Перспектива стати бригадиром"],
    "details_pl": ["Diety wyjazdowe", "Pomoc z zakwaterowaniem w delegacji", "Perspektywa awansu na brygadzistę"],
    "details_ru": ["Командировочные выплаты (диеты)", "Помощь с жильем в командировках", "Перспектива стать бригадиром"],
    "is_generated": False,
    "data_source": "manual",
    "seo_title_ua": "Монтажник сонячних панелей Бидгощ",
    "seo_title_pl": "Instalator fotowoltaiki Bydgoszcz",
    "seo_title_ru": "Монтажник солнечных панелей Быдгощ",
    "seo_title_en": "Solar panel installer Bydgoszcz"
  }
]

with open("src/content.json", "r", encoding="utf-8") as f:
    data = json.load(f)

data.extend(new_vacancies)

with open("src/content.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Successfully added 10 new vacancies. New total: {len(data)}")
