export const translations = {
  uk: {
    navAria: 'Головна навігація',
    navHome: 'Головна',
    navSpecialists: 'Спеціалісти',
    navStartups: 'Стартапи',
    navMethodology: 'Методологія',
    navFaq: 'Питання й відповіді',
    navInterview: 'Тренажер співбесіди',
    navMenu: 'Меню',
    navPrivacy: 'Конфіденційність',
    navCookies: 'Cookies',
    navTerms: 'Умови',
    skipLink: 'Перейти до основного вмісту',
    brandTagline: 'Редакційний атлас людей і компаній',
    contactLabel: 'Написати:',
    footerAbout:
      'Редакційний довідник Rybezh.site: короткі профілі фахівців, керівників і технологічних компаній, з виходом на первинні джерела.',
    footerNavTitle: 'Навігація',
    footerScopeTitle: 'Про базу',
    footerScopeText:
      'Матеріали для орієнтації в темі; це не стрічка новин і не майданчик вакансій. Факти звіряйте з офіційними сайтами та публікаціями.',
    footerLanguages: 'Мови: українська, англійська, іспанська, російська.',
    footerRights: 'Усі права захищені.',
    footerPoliciesTitle: 'Політики',
    footerPoliciesText:
      'Сторінки про конфіденційність, cookies та умови; як збираємо матеріали — у розділі «Методологія»; типові запитання — у «Питання й відповіді».',
    footerTagline: 'Первинні джерела завжди мають пріоритет перед цим довідником.',
    footerSitemap: 'Карта сайту',
    cookieTitle: 'Ми використовуємо лише базові cookies',
    cookieText:
      'Сайт зберігає в браузері вибір теми та вашу відповідь щодо cookies. Деталі — на сторінці політики cookies.',
    cookieAccept: 'Прийняти',
    cookieDecline: 'Відхилити',
    searchAria: 'Пошук по всьому сайту',
    searchPlaceholder: 'Пошук: імʼя, компанія, сторінка…',
    searchBadgePerson: 'Спеціаліст',
    searchBadgeStartup: 'Стартап',
    searchBadgePage: 'Сторінка',
    searchEmpty: 'Нічого не знайдено',
    searchHint: 'результатів у списку'
  },
  en: {
    navAria: 'Main navigation',
    navHome: 'Home',
    navSpecialists: 'Specialists',
    navStartups: 'Startups',
    navMethodology: 'Methodology',
    navFaq: 'FAQ',
    navInterview: 'Interview drill',
    navMenu: 'Menu',
    navPrivacy: 'Privacy',
    navCookies: 'Cookies',
    navTerms: 'Terms',
    skipLink: 'Skip to main content',
    brandTagline: 'Editorial atlas of people and companies',
    contactLabel: 'Email:',
    footerAbout:
      'Rybezh.site is an editorial directory of specialists, leaders, and tech companies—short entries that point to primary sources.',
    footerNavTitle: 'Navigation',
    footerScopeTitle: 'About this site',
    footerScopeText:
      'Reference-style pages for context; not a news feed or a jobs board. Cross-check facts on official sites and publications.',
    footerLanguages: 'Languages: Ukrainian, English, Spanish, Russian.',
    footerRights: 'All rights reserved.',
    footerPoliciesTitle: 'Policies',
    footerPoliciesText:
      'Privacy, cookies, and terms pages are linked above; methodology is explained in its own section, and common questions in the FAQ.',
    footerTagline: 'Primary sources outweigh this directory when they disagree.',
    footerSitemap: 'Sitemap',
    cookieTitle: 'We use only basic cookies',
    cookieText:
      'The site stores your theme choice and cookie-banner response in the browser. See the cookies policy for details.',
    cookieAccept: 'Accept',
    cookieDecline: 'Decline',
    searchAria: 'Site-wide search',
    searchPlaceholder: 'Search people, companies, pages…',
    searchBadgePerson: 'Specialist',
    searchBadgeStartup: 'Company',
    searchBadgePage: 'Page',
    searchEmpty: 'No matches',
    searchHint: 'results in list'
  },
  es: {
    navAria: 'Navegación principal',
    navHome: 'Inicio',
    navSpecialists: 'Especialistas',
    navStartups: 'Startups',
    navMethodology: 'Metodología',
    navFaq: 'Preguntas frecuentes',
    navInterview: 'Simulacro de entrevista',
    navMenu: 'Menú',
    navPrivacy: 'Privacidad',
    navCookies: 'Cookies',
    navTerms: 'Términos',
    skipLink: 'Ir al contenido principal',
    brandTagline: 'Atlas editorial de personas y empresas',
    contactLabel: 'Correo:',
    footerAbout:
      'Rybezh.site es un directorio editorial sobre especialistas, directivos y empresas tecnológicas, con enlaces a fuentes primarias.',
    footerNavTitle: 'Navegación',
    footerScopeTitle: 'Sobre el sitio',
    footerScopeText:
      'Textos de referencia para orientarte; no es un medio de noticias ni un portal de empleo. Contrasta los datos en fuentes oficiales.',
    footerLanguages: 'Idiomas: ucraniano, inglés, español y ruso.',
    footerRights: 'Todos los derechos reservados.',
    footerPoliciesTitle: 'Políticas',
    footerPoliciesText:
      'Páginas de privacidad, cookies y términos enlazadas arriba; la metodología está en su propia sección y las dudas frecuentes en Preguntas frecuentes.',
    footerTagline: 'Si hay discrepancia, prevalecen las fuentes primarias.',
    footerSitemap: 'Mapa del sitio',
    cookieTitle: 'Usamos solo cookies básicas',
    cookieText:
      'El sitio guarda en el navegador el tema y tu respuesta al aviso de cookies. Más información en la política de cookies.',
    cookieAccept: 'Aceptar',
    cookieDecline: 'Rechazar',
    searchAria: 'Búsqueda en el sitio',
    searchPlaceholder: 'Buscar personas, empresas, páginas…',
    searchBadgePerson: 'Especialista',
    searchBadgeStartup: 'Empresa',
    searchBadgePage: 'Página',
    searchEmpty: 'Sin resultados',
    searchHint: 'resultados en la lista'
  },
  ru: {
    navAria: 'Главная навигация',
    navHome: 'Главная',
    navSpecialists: 'Специалисты',
    navStartups: 'Стартапы',
    navMethodology: 'Методология',
    navFaq: 'Вопросы и ответы',
    navInterview: 'Тренажёр собеседования',
    navMenu: 'Меню',
    navPrivacy: 'Конфиденциальность',
    navCookies: 'Cookies',
    navTerms: 'Условия',
    skipLink: 'Перейти к основному содержимому',
    brandTagline: 'Редакционный атлас людей и компаний',
    contactLabel: 'Почта:',
    footerAbout:
      'Редакционный справочник Rybezh.site: краткие заметки о специалистах, руководителях и технологических компаниях, со ссылками на первоисточники.',
    footerNavTitle: 'Навигация',
    footerScopeTitle: 'О сайте',
    footerScopeText:
      'Материалы для ориентира, это не новостная лента и не площадка вакансий. Факты сверяйте с официальными сайтами и публикациями.',
    footerLanguages: 'Языки: украинский, английский, испанский, русский.',
    footerRights: 'Все права защищены.',
    footerPoliciesTitle: 'Политики',
    footerPoliciesText:
      'Страницы о конфиденциальности, cookies и условиях — в ссылках выше; как собираем материалы — в разделе «Методология»; типичные вопросы — в «Вопросы и ответы».',
    footerTagline: 'При расхождении приоритет у первичных источников.',
    footerSitemap: 'Карта сайта',
    cookieTitle: 'Мы используем только базовые cookies',
    cookieText:
      'Сайт сохраняет в браузере выбор темы и ваш ответ по cookies. Подробности — на странице политики cookies.',
    cookieAccept: 'Принять',
    cookieDecline: 'Отклонить',
    searchAria: 'Поиск по сайту',
    searchPlaceholder: 'Поиск: имя, компания, страница…',
    searchBadgePerson: 'Специалист',
    searchBadgeStartup: 'Компания',
    searchBadgePage: 'Страница',
    searchEmpty: 'Ничего не найдено',
    searchHint: 'результатов в списке'
  }
};

export const editorialUi = {
  uk: {
    navDockAria: 'Швидка навігація',
    cmdOpenAria: 'Відкрити палітру пошуку',
    cmdHint: 'Натисніть / або Ctrl+K',
    cmdTitle: 'Пошук по Rybezh',
    cmdClose: 'Закрити',
    cmdRecent: 'Недавні запити',
    cmdSuggested: 'Підказки',
    filterAll: 'Усе',
    filterPeople: 'Люди',
    filterCompanies: 'Компанії',
    filterPages: 'Сторінки',
    breadcrumbAria: 'Навігаційний шлях',
    intelAsideAria: 'Редакційний контекст',
    timelineTitle: 'Лінія ролей',
    timelineNow: 'Поточний опис у картці',
    timelineDesk: 'Знімок файлу',
    expertiseTitle: 'Граф експертизи',
    influenceTitle: 'Зони впливу',
    influenceIntro: 'Теги з профілю зібрані як сигнал тем — не формальна класифікація.',
    sourcesTitle: 'Зовнішні посилання',
    sourcesIntro: 'Поза Rybezh; первинні матеріали звіряйте на оригінальних сторінках.',
    verifyTitle: 'Як перевіряємо',
    verifyBody:
      'Запис збирається з публічних джерел і проходить редакційний прохід. У розбіжностях пріоритет у первинних матеріалах.',
    lastUpdated: 'Остання зміна файлу',
    deskNoteTitle: 'Редакційна нотатка',
    deskNoteBody: 'Короткий орієнтир для читання — не біографія й не оцінка заслуг.',
    orgIntelAsideAria: 'Редакційний контекст компанії',
    orgTimelineTitle: 'Ключові опори',
    orgTimelineProduct: 'Продуктовий фокус у картці',
    orgTimelineDesk: 'Знімок файлу'
  },
  en: {
    navDockAria: 'Quick navigation',
    cmdOpenAria: 'Open search palette',
    cmdHint: 'Press / or Ctrl+K',
    cmdTitle: 'Search Rybezh',
    cmdClose: 'Close',
    cmdRecent: 'Recent queries',
    cmdSuggested: 'Suggestions',
    filterAll: 'All',
    filterPeople: 'People',
    filterCompanies: 'Companies',
    filterPages: 'Pages',
    breadcrumbAria: 'Breadcrumb',
    intelAsideAria: 'Editorial context',
    timelineTitle: 'Role timeline',
    timelineNow: 'Current framing on this card',
    timelineDesk: 'File snapshot',
    expertiseTitle: 'Expertise map',
    influenceTitle: 'Influence areas',
    influenceIntro: 'Tags from the card grouped as a light signal of themes—not a formal taxonomy.',
    sourcesTitle: 'External references',
    sourcesIntro: 'Outside Rybezh; verify primary material at the source.',
    verifyTitle: 'Verification',
    verifyBody:
      'Compiled from public sources and edited for clarity. Primary sources win when facts diverge.',
    lastUpdated: 'Last file update',
    deskNoteTitle: 'Editorial note',
    deskNoteBody: 'A concise briefing for reading—not a biography or an awards list.',
    orgIntelAsideAria: 'Company editorial context',
    orgTimelineTitle: 'Anchors',
    orgTimelineProduct: 'Product focus on this card',
    orgTimelineDesk: 'File snapshot'
  },
  es: {
    navDockAria: 'Navegación rápida',
    cmdOpenAria: 'Abrir paleta de búsqueda',
    cmdHint: 'Pulsa / o Ctrl+K',
    cmdTitle: 'Buscar en Rybezh',
    cmdClose: 'Cerrar',
    cmdRecent: 'Búsquedas recientes',
    cmdSuggested: 'Sugerencias',
    filterAll: 'Todo',
    filterPeople: 'Personas',
    filterCompanies: 'Empresas',
    filterPages: 'Páginas',
    breadcrumbAria: 'Migas de pan',
    intelAsideAria: 'Contexto editorial',
    timelineTitle: 'Línea de roles',
    timelineNow: 'Encuadre actual en la ficha',
    timelineDesk: 'Instantánea del archivo',
    expertiseTitle: 'Mapa de expertise',
    influenceTitle: 'Áreas de influencia',
    influenceIntro: 'Etiquetas agrupadas como señal temática ligera, no taxonomía formal.',
    sourcesTitle: 'Referencias externas',
    sourcesIntro: 'Fuera de Rybezh; contrasta el material primario en origen.',
    verifyTitle: 'Verificación',
    verifyBody:
      'Compilado desde fuentes públicas y editado para claridad. Las fuentes primarias prevalecen si hay discrepancias.',
    lastUpdated: 'Última actualización del archivo',
    deskNoteTitle: 'Nota editorial',
    deskNoteBody: 'Resumen breve para lectura: no es biografía ni palmarés.',
    orgIntelAsideAria: 'Contexto editorial de la empresa',
    orgTimelineTitle: 'Anclas',
    orgTimelineProduct: 'Foco de producto en la ficha',
    orgTimelineDesk: 'Instantánea del archivo'
  },
  ru: {
    navDockAria: 'Быстрая навигация',
    cmdOpenAria: 'Открыть палитру поиска',
    cmdHint: 'Нажмите / или Ctrl+K',
    cmdTitle: 'Поиск по Rybezh',
    cmdClose: 'Закрыть',
    cmdRecent: 'Недавние запросы',
    cmdSuggested: 'Подсказки',
    filterAll: 'Всё',
    filterPeople: 'Люди',
    filterCompanies: 'Компании',
    filterPages: 'Страницы',
    breadcrumbAria: 'Навигационная цепочка',
    intelAsideAria: 'Редакционный контекст',
    timelineTitle: 'Линия ролей',
    timelineNow: 'Текущее описание в карточке',
    timelineDesk: 'Снимок файла',
    expertiseTitle: 'Карта экспертизы',
    influenceTitle: 'Зоны влияния',
    influenceIntro: 'Теги из карточки как лёгкий сигнал тем — не формальная классификация.',
    sourcesTitle: 'Внешние ссылки',
    sourcesIntro: 'Вне Rybezh; первичные материалы сверяйте на оригинальных страницах.',
    verifyTitle: 'Как проверяем',
    verifyBody:
      'Материал собран из публичных источников и проходит редакционную вычитку. При расхождениях приоритет у первичных источников.',
    lastUpdated: 'Последнее изменение файла',
    deskNoteTitle: 'Редакционная заметка',
    deskNoteBody: 'Краткий ориентир для чтения — не биография и не список наград.',
    orgIntelAsideAria: 'Редакционный контекст компании',
    orgTimelineTitle: 'Опорные точки',
    orgTimelineProduct: 'Продуктовый фокус в карточке',
    orgTimelineDesk: 'Снимок файла'
  }
};
