// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/interview-lab/InterviewLab.tsx": () => import("../components/mockups/interview-lab/InterviewLab.tsx")
};
