/**
 * Remove AI / artificial-intelligence wording from public-facing catalogue text.
 * Shared by generate_data.js and generate_profiles.js.
 */
export function stripAiPublicText(text) {
  let s = String(text ?? '');
  const reps = [
    [/искусственный\s+интеллект/giu, 'системы обработки данных'],
    [/штучн(ий|ого)\s+інтелект/giu, 'системи обробки даних'],
    [/Inteligencia\s+artificial/giu, 'sistemas computacionales'],
    [/inteligencia\s+artificial/giu, 'sistemas computacionales'],
    [/\bartificial\s+intelligence\b/giu, 'computing systems'],
    [/\bArtificial\s+intelligence\b/gu, 'Computing systems'],
    [/\bmachine\s+learning\b/giu, 'predictive modelling'],
    [/\bdeep\s+learning\b/giu, 'statistical modelling'],
    [/\bgenerative\s+AI\b/giu, 'generative computing'],
    [/\bgenerative\s+artificial\s+intelligence\b/giu, 'generative computing'],
    [/\bAI\s+safety\b/giu, 'system safety'],
    [/\bAI\s+researcher\b/giu, 'computing researcher'],
    [/\bAI\s+research\b/giu, 'computing research'],
    [/\bAI\s+researchers\b/giu, 'computing researchers'],
    [/\bAI\s+models\b/giu, 'large computing models'],
    [/\bAI\s+model\b/giu, 'computing model'],
    [/\bAI\s+platforms?\b/giu, 'computing platforms'],
    [/\bAI\s+platform\b/giu, 'computing platform'],
    [/\bAI\s+computing\b/giu, 'accelerated computing'],
    [/\bAI\s+features\b/giu, 'automation features'],
    [/\bAI\s+automation\b/giu, 'workflow automation'],
    [/\bAI\s+strategy\b/giu, 'platform strategy'],
    [/\bAI\s+infrastructure\b/giu, 'data infrastructure'],
    [/\bAI\s+integration\b/giu, 'platform integration'],
    [/\bAI\s+entrepreneur\b/giu, 'technology entrepreneur'],
    [/\bAI\s+entrepreneurs\b/giu, 'technology entrepreneurs'],
    [/\bAI\s+systems?\b/giu, 'computing systems'],
    [/\bAI\s+lab\b/giu, 'research lab'],
    [/\bAI\s+labs\b/giu, 'research labs'],
    [/\bAI\s+executive\b/giu, 'technology executive'],
    [/\bAI\s+technology\b/giu, 'computing technology'],
    [/\bAI\s+for\s+CRM\b/giu, 'computing for CRM'],
    [/\bAI-assisted\b/giu, 'tool-assisted'],
    [/\bAI-related\b/giu, 'platform-related'],
    [/\bAI breakthroughs\b/giu, 'computing breakthroughs'],
    [/\bAI breakthrough\b/giu, 'computing breakthrough'],
    [/\bAI-напрям/giu, 'напрям обчислювальних продуктів'],
    [/\bAI-направлен/giu, 'вычислительн'],
    [/\bAI-функц/giu, 'функц'],
    [/\bAI-функції\b/giu, 'функції автоматизації'],
    [/\bAI-функции\b/giu, 'функции автоматизации'],
    [/\bAI-автоматизац/giu, 'автоматизац'],
    [/\bAI-автоматизація\b/giu, 'автоматизація процесів'],
    [/\bAI-підприємц/giu, 'технологічних підприємц'],
    [/\bAI-предпринимател/giu, 'технологических предпринимател'],
    [/\bAI-платформ/giu, 'платформ обробки даних'],
    [/\bAI-модел/giu, 'модел'],
    [/\bAI-моделей\b/giu, 'обчислювальних моделей'],
    [/\bAI-модели\b/giu, 'вычислительных моделей'],
    [/\bAI-стартап/giu, 'технологічний стартап'],
    [/\bAI-стартапів\b/giu, 'технологічних стартапів'],
    [/\bAI-стартапов\b/giu, 'технологических стартапов'],
    [/\bAI-инфраструктур/giu, 'инфраструктур обработки данных'],
    [/\bAI-исследован/giu, 'исследован в области вычислительных систем'],
    [/\bAI-досліджень\b/giu, 'досліджень у сфері обчислювальних систем'],
    [/\bAI-дослідження\b/giu, 'обчислювальні дослідження'],
    [/\bAI\s+products\b/giu, 'computing products'],
    [/\bMicrosoft\s+AI\b/gu, 'Microsoft computing division'],
    [/\bCEO\s+Microsoft\s+AI\b/gu, 'CEO of Microsoft computing division'],
    [/\bCEO\s+of\s+Microsoft\s+AI\b/gu, 'CEO of Microsoft computing division'],
    [/\bCEO\s+Salesforce\s+AI\b/gu, 'CEO of Salesforce computing division'],
    [/\bCEO\s+of\s+Salesforce\s+AI\b/gu, 'CEO of Salesforce computing division'],
    [/\bCloud\s*\+\s*AI\s+Group\b/giu, 'Cloud and computing group'],
    [/\bdata\/AI\b/giu, 'data and computing'],
    [/\bdata\s+and\s+AI\b/giu, 'data and computing'],
    [/\bOpenAI\b/gu, 'Open Technologies Lab'],
    [/\bMistral\s+AI\b/gu, 'Mistral'],
    [/\bCohere\s+for\s+AI\b/gu, 'Cohere research group'],
    [/\bInflection\s+AI\b/gu, 'Inflection'],
    [/\bGoogle\s+AI\b/gu, 'Google computing'],
    [/\bChatGPT\b/gu, 'Chat product'],
    [/\bLLM\b/gu, 'large language models'],
    [/\bLLMs\b/gu, 'large language models'],
    [/\bGPT\b/gu, 'language model family'],
    [/\bCopilot\b/gu, 'assistant tools'],
    [/\bTensorFlow\b/gu, 'TensorFlow'],
    [/\bresponsible\s+AI\b/giu, 'responsible computing'],
    [/\bhuman-centred\s+AI\b/giu, 'human-centred computing'],
    [/\bhuman-centered\s+AI\b/giu, 'human-centered computing'],
    [/\bhuman-centred\s+computing\b/giu, 'human-centred computing'],
    [/\bcomputing\s+computing\b/giu, 'computing'],
    [/\bcomputing\s+systems\s+systems\b/giu, 'computing systems'],
    [/дослідник\s+шІ/giu, 'дослідник обробки даних'],
    [/Дослідник\s+шІ/giu, 'Дослідник обробки даних'],
    [/дослідниця\s+шІ/giu, 'дослідниця обробки даних'],
    [/Дослідниця\s+шІ/giu, 'Дослідниця обробки даних'],
    [/дослідницька\s+компанія\s+шІ/giu, 'дослідницька компанія з обробки даних'],
    [/Дослідницька\s+компанія\s+шІ/giu, 'Дослідницька компанія з обробки даних'],
    [/лабораторія\s+шІ/giu, 'лабораторія обробки даних'],
    [/Лабораторія\s+шІ/giu, 'Лабораторія обробки даних'],
    [/open-source\s+платформа\s+шІ/giu, 'open-source платформа обробки даних'],
    [/Open-source\s+платформа\s+шІ/giu, 'Open-source платформа обробки даних'],
    [/відповідальний\s+шІ/giu, 'відповідальні обчислювальні системи'],
    [/Відповідальний\s+шІ/giu, 'Відповідальні обчислювальні системи'],
    [/людськоцентричний\s+шІ/giu, 'людськоцентричні обчислювальні системи'],
    [/безпека\s+шІ/giu, 'безпека обчислювальних систем'],
    [/Безпека\s+шІ/giu, 'Безпека обчислювальних систем'],
    [/генеративний\s+шІ/giu, 'генеративні обчислювальні інструменти'],
    [/Генеративний\s+шІ/giu, 'Генеративні обчислювальні інструменти'],
    [/у\s+сфері\s+шІ/giu, 'у сфері обробки даних'],
    [/У\s+сфері\s+шІ/giu, 'У сфері обробки даних'],
    [/для\s+шІ/giu, 'для обробки даних'],
    [/Для\s+шІ/giu, 'Для обробки даних'],
    [/системи\s+шІ/giu, 'системи обробки даних'],
    [/Системи\s+шІ/giu, 'Системи обробки даних'],
    [/ключову\s+платформу\s+для\s+шІ/giu, 'ключову платформу обробки даних'],
    [/перетворення\s+NVIDIA\s+на\s+ключову\s+платформу\s+для\s+шІ/giu, 'перетворення NVIDIA на ключову платформу обробки даних'],
    [/исследовательница\s+ии/giu, 'исследовательница вычислительных систем'],
    [/Исследовательница\s+ии/giu, 'Исследовательница вычислительных систем'],
    [/исследователь\s+ии/giu, 'исследователь вычислительных систем'],
    [/Исследователь\s+ии/giu, 'Исследователь вычислительных систем'],
    [/ответственный\s+ии/giu, 'ответственные вычислительные системы'],
    [/Ответственный\s+ии/giu, 'Ответственные вычислительные системы'],
    [/человекоцентричным\s+ии/giu, 'человекоцентричными вычислительными системами'],
    [/лаборатория\s+ии/giu, 'лаборатория обработки данных'],
    [/Лаборатория\s+ии/giu, 'Лаборатория обработки данных'],
    [/исследовательская\s+компания\s+ии/giu, 'исследовательская компания по обработке данных'],
    [/Исследовательская\s+компания\s+ии/giu, 'Исследовательская компания по обработке данных'],
    [/open-source\s+платформа\s+ии/giu, 'open-source платформа обработки данных'],
    [/Open-source\s+платформа\s+ии/giu, 'Open-source платформа обработки данных'],
    [/безопасность\s+ии/giu, 'безопасность вычислительных систем'],
    [/генеративного\s+ии/giu, 'генеративных вычислительных инструментов'],
    [/генеративный\s+ии/giu, 'генеративные вычислительные инструменты'],
    [/в\s+сфере\s+ии/giu, 'в сфере обработки данных'],
    [/В\s+сфере\s+ии/giu, 'В сфере обработки данных'],
    [/для\s+ии/giu, 'для обработки данных'],
    [/Для\s+ии/giu, 'Для обработки данных'],
    [/системами\s+ии/giu, 'системами обработки данных'],
    [/Системами\s+ии/giu, 'Системами обработки данных'],
    [/над\s+фундаментальными\s+системами\s+ии/giu, 'над фундаментальными вычислительными системами'],
    [/Работает\s+над\s+фундаментальными\s+системами\s+ии/giu, 'Работает над фундаментальными вычислительными системами'],
    [/расширение\s+ии/giu, 'расширение вычислительных систем'],
    [/Расширение\s+ии/giu, 'Расширение вычислительных систем'],
    [/фундаментальные\s+системы\s+ии/giu, 'фундаментальные вычислительные системы'],
    [/Фундаментальные\s+системы\s+ии/giu, 'Фундаментальные вычислительные системы'],
    [/фундаментальними\s+системами\s+ии/giu, 'фундаментальными вычислительными системами'],
    [/модели\s+и\s+продукты\s+ии/giu, 'модели и продукты обработки данных'],
    [/Модели\s+и\s+продукты\s+ии/giu, 'Модели и продукты обработки данных'],
    [/открытые\s+и\s+коммерческие\s+модели\s+ии/giu, 'открытые и коммерческие модели обработки данных'],
    [/Строит\s+открытые\s+и\s+коммерческие\s+модели\s+ии/giu, 'Строит открытые и коммерческие модели обработки данных'],
    [/движение\s+ии/giu, 'движение вычислительных систем'],
    [/фундаментальними\s+системами\s+шІ/giu, 'фундаментальними обчислювальними системами'],
    [/фундаментальні\s+системи\s+шІ/giu, 'фундаментальні обчислювальні системи'],
    [/Фундаментальні\s+системи\s+шІ/giu, 'Фундаментальні обчислювальні системи'],
    [/відкриті\s+та\s+комерційні\s+моделі\s+шІ/giu, 'відкриті та комерційні моделі обробки даних'],
    [/Будує\s+відкриті\s+та\s+комерційні\s+моделі\s+шІ/giu, 'Будує відкриті та комерційні моделі обробки даних'],
    [/інженер\s+систем\s+шІ/giu, 'інженер обчислювальних систем'],
    [/Інженер\s+систем\s+шІ/giu, 'Інженер обчислювальних систем'],
    [/моделі\s+шІ/giu, 'моделі обробки даних'],
    [/Моделі\s+шІ/giu, 'Моделі обробки даних'],
    [/продукти\s+шІ/giu, 'продукти обробки даних'],
    [/Продукти\s+шІ/giu, 'Продукти обробки даних'],
    [/обробки\s+даниху/giu, 'обробки даних'],
    [/обробки\s+данихы/giu, 'обробки даних'],
    [/исследован\s+в\s+области\s+вычислительных\s+системия/giu, 'исследований в области вычислительных систем'],
    [/\bAI\b/g, 'computing'],
    [/\bIA\b/g, 'computación'],
    [/\bШІ\b/gu, 'обробка даних'],
    [/\bштучн(ий|ого)\s+інтелект\b/giu, 'обробка даних'],
    [/\bШІ-/gu, ''],
    [/\bcomputing\s+computing\b/giu, 'computing']
  ];
  for (const [re, to] of reps) {
    s = s.replace(re, to);
  }
  s = s.replace(/\bcomputing(?:\s+computing)+\b/giu, 'computing');
  const tailFixes = [
    [/прорывы\s+ии/giu, 'прорывы вычислительных систем'],
    [/прориви\s+шІ/giu, 'прориви обчислювальних систем'],
    [/данихи\b/giu, 'даних'],
    [/данихы\b/giu, 'даних'],
    [/даниху\b/giu, 'даних'],
    [/системия\b/giu, 'систем'],
    [/прогресс\s+ии/giu, 'прогресс вычислительных систем'],
    [/Прогресс\s+ии/giu, 'Прогресс вычислительных систем'],
    [/майбутнє\s+шІ/giu, 'майбутнє обробки даних'],
    [/Майбутнє\s+шІ/giu, 'Майбутнє обробки даних'],
    [/генеративного\s+шІ/giu, 'генеративних обчислювальних інструментів'],
    [/Генеративного\s+шІ/giu, 'Генеративних обчислювальних інструментів'],
    [/європейський\s+ринок\s+генеративного\s+шІ/giu, 'європейський ринок генеративних обчислювальних інструментів'],
    [/VR\s+и\s+ии/giu, 'VR и вычислительных систем'],
    [/инвестиции\s+в\s+VR\s+и\s+ии/giu, 'инвестиции в VR и вычислительные системы'],
    [/масштабирование\s+ии/giu, 'масштабирование вычислительных систем'],
    [/операционное\s+масштабирование\s+ии/giu, 'операционное масштабирование вычислительных систем'],
    [/встраивание\s+ии/giu, 'встраивание вычислительных систем'],
    [/интеграции\s+ии/giu, 'интеграции вычислительных систем'],
    [/исследования\s+ии/giu, 'исследования вычислительных систем'],
    [/Исследования\s+ии/giu, 'Исследования вычислительных систем'],
    [/где\s+ии/giu, 'где вычислительные системы'],
    [/Где\s+ии/giu, 'Где вычислительные системы'],
    [/ии\s+внутри/giu, 'вычислительных систем внутри'],
    [/ИИ\s+внутри/giu, 'вычислительных систем внутри'],
    [/la\s+sistemas/giu, 'la computación'],
    [/de\s+la\s+sistemas/giu, 'de la computación'],
    [/donde\s+la\s+sistemas/giu, 'donde la computación'],
    [/progreso\s+de\s+la\s+sistemas/giu, 'progreso de la computación'],
    [/sistemas\s+responsable\b/giu, 'sistemas responsables'],
    [/sistemas\s+centrada/giu, 'computación centrada'],
    [/despliegue\s+responsable\s+de\s+la\s+sistemas\s+generativa/giu, 'despliegue responsable de la computación generativa'],
    [/despliegue\s+responsable\s+de\s+la\s+sistemas/giu, 'despliegue responsable de la computación'],
    [/el\s+debate\s+sobre\s+el\s+escalamiento\s+de\s+la\s+sistemas/giu, 'el debate sobre el escalamiento de la computación'],
    [/desarrollo\s+asistido\s+por\s+sistemas/giu, 'desarrollo asistido por herramientas'],
    [/donde\s+la\s+sistemas\s+cambia/giu, 'donde la computación cambia']
  ];
  for (const [re, to] of tailFixes) {
    s = s.replace(re, to);
  }
  s = s.replace(/(?<![\p{L}\p{M}])ИИ(?![\p{L}\p{M}])/gu, 'вычислительных систем');
  s = s.replace(/(?<![\p{L}\p{M}])ШІ(?![\p{L}\p{M}])/gu, 'обчислювальні системи');
  return s.replace(/\s+/g, ' ').trim();
}
